### ISSUE TITLE
Error on default task

### ISSUE THREAD

**Issue by paulocheque** [yeoman/generator-polymer#179]
Every task run without errors, but when I ran the default task (it simply run a list of subtasks), I got this:

    Error: [object Object]
        at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
        at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
        at Gulp.emit (events.js:129:20)
        at Gulp.Orchestrator._emitTaskDone (.../node_modules/gulp/node_modules/orchestrator/index.js:264:8)
        at .../node_modules/gulp/node_modules/orchestrator/index.js:275:23
        at finish (.../node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
        at cb (.../node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
        at finish (.../node_modules/run-sequence/index.js:38:5)
        at Gulp.onError (.../node_modules/run-sequence/index.js:45:4)
        at Gulp.emit (events.js:129:20)
        at Gulp.Orchestrator._emitTaskDone (.../node_modules/gulp/node_modules/orchestrator/index.js:264:8)
        at .../node_modules/gulp/node_modules/orchestrator/index.js:275:23
        at finish (.../node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
        at DestroyableTransform.<anonymous> (.../node_modules/gulp/node_modules/orchestrator/lib/runTask.js:52:4)
        at DestroyableTransform.f (.../node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/node_modules/once/once.js:17:25)
        at DestroyableTransform.emit (events.js:129:20)

Any ideas?

Thanks in advance

**Comment by paulocheque** [comment]
It appears it was caused by JSLint errors. It was just a bad error msg.

**Comment by arthurvr** [comment]
> It appears it was caused by JSLint errors. It was just a bad error msg.

We don't use JSLint in this generator.
