### ISSUE TITLE
Spawn Error

### ISSUE THREAD

**Issue by waltercolindres** [yeoman/generator-polymer#186]
Just downloaded the latest from the repo and did a gulp serve:

You should re-install spawn-sync if possible.
Check /Users/XXXXX/Desktop/my-project/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/bin-check/node_modules/spawn-sync/error.log for more details
[11:58:37] 'elements' all files 0 B
[11:58:37] Finished 'elements' after 1.06 s
Unhandled rejection Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)
Unhandled rejection Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)
[11:58:37] 'styles' all files 98 B
[11:58:37] Finished 'styles' after 1.53 s

I manually installed spawn sync and it still failed. Any help would be appreciated!

**Comment by waltercolindres** [comment]
I've checked for the error.log file and it does not exist.

**Comment by kevva** [comment]
node version?

**Comment by addyosmani** [comment]
Fyi, this issue is also most likely https://github.com/PolymerElements/polymer-starter-kit/issues/101. 

@waltercolindres Does this get any better with an `npm cache clean` followed by a re-install?

**Comment by waltercolindres** [comment]
That work @addyosmani! Thanks
