### ISSUE TITLE
gulp serve is not working 

### ISSUE THREAD

**Issue by sajjadmurtaza-ror** [yeoman/generator-polymer#239]
i follow these steps
Download polymer-starter-kit and extract cd polymer-starter-kit.
npm install
bowser install
cd polymer-starter-kit-light
python -m SimpleHTTPServer 8080

Working great for me.

But for Yeoman user?

npm install -g generator-polymer
mkdir -p my-project && cd $_
yo polymer
yo polymer:el my-element

every thing is great  but  gulp serve is not working

**Comment by samccone** [comment]
@sajjadmurtaza49 can you put the error you are seeing?

**Comment by sajjadmurtaza49** [comment]
gulp serve               
module.js:338
    throw err;
          ^
Error: Cannot find module 'browser-sync'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/sajad/polymers/polymer-starter-kit-1.1.1/gulpfile.js:17:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by arthurvr** [comment]
You probably just got an installation error. Try deleting the `node_modules` folder and `npm install`ing again.

**Comment by sajjadmurtaza49** [comment]
I did but same issue

**Comment by ragingwind** [comment]
@sajjadmurtaza49 You definitely have errors as you installed npm dependencies according to your error message. Installation has not been completed well. Firstly, check your environments of npm / node then make sure that install dependencies with no errors.
